apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: haiku-api-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: haiku-api-role
subjects:
- kind: ServiceAccount
  name: haiku-api
  namespace: haiku-api
